#!/usr/bin/python3


import sys, os


file = sys.argv[1]
base = os.path.basename(sys.argv[2])

print("perf script...")
os.system("perf script -i %s | ~/bin/FlameGraph/stackcollapse-perf.pl > ./%s.perf-folded" % (file, base))

print("making graph...")
os.system("~/bin/FlameGraph/flamegraph.pl ./%s.perf-folded > ./%s.svg" % (base, base))

print("made: %s.svg" % base)

os.system("firefox %s.svg" % base)